---
title: "About this blog"
description: |
  Hi, this is my practice corner for coding in R.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

About this blog: a place to code and build portfolio.
About me: food scientist, used to analyse data with Excel and SPSS before I met R. Attended a short modular course on R and want to build and expand on what I have learnt. 

*Aristotle — 'The more you know, the more you know you don't know.'*

and that makes me want to learn even more. 

I tried to look for a chemometrics course that I can take online, but found that there wasn't any suitable one avaible in Singapore. Most of the chemometrics courses were catered for PHD or Masters students already enrolled in overseas universities, or were data science machine learning courses for other domains such as fintech. 

What I would like to achieve for this blog, is a self-practice corner to compile my codes, for the following application areas:

- Design of experiment: Full factorial design, half factorial design, optimisation. This could be applied to design of chemistry experiments, or even sensory analysis.
- Signal pre-processing (for chromatographic, spectral data)
- Univariate statistical analysis
- Multivariate statistical analysis
- PCA as exploratory method to remove redundant variables (unsupervised method)
- Modelling for classification - PLS-DA, kNN, QDA, LDA
- Modelling for regression - PLS-R, PCR, OLS-R

Most of the statistical software are expensive and not readily available to resource-tight individuals in companies or students. R and Python are open-source software with powerful packages and allows customization of graphs, but requires a certain level of coding knowledge. This will be the area I want to specialize in: Chemometrics with R.
